opendistro-for-elasticsearch/perftop

.npmignore, package.json
=> Publish to npm

README.md, package-lock.json
=> Minor README fix

release-notes
=> Add release notes for 0.9

build.gradle, package-lock.json, package.json
=> Upgrade artifact version to 0.9

README.md, package-lock.json, package.json, release-notes
=> Version upgrade and remove package vulnerabilities.

package.json
=> Update version 1.0.0 on package.json

package-lock.json
=> Fix lodash

build.gradle, package-lock.json, package.json, release-notes
Version upgrade and fix vulnerabilities.
=> Opendistro 1.1

build.gradle, release-notes
1. Updating the opendistro version for PerfTop
2. Updating the release notes for PerfTop
=> Update PerfTop to support OpenDistro 0.10 release

package-lock.json, package.json
1. Bumped version for npm artifact.
2. audit-fixed vulnerabilities
=> Fix npm version and fix vulnerabilities

build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes
=> Update PerfTop to support OpenDistro 1.2.1 release

build.gradle, package-lock.json, package.json, release-notes
Bumping up version and updated the release notes.
Fixed vulnerabilities detected by npm audit
=> Bump version and fix vulnerabilities

.github/workflows/cd.yml
And cd.yml and enable CD pipeline to upload artifact to S3
=> Add cd.yml and enable CD pipeline to upload artifact to S3

build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes
Add support for ODFE 1.7 (Elasticsearch v7.7.0)
=> Add support for ODFE 1.7 (Elasticsearch v7.7.0)

build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes
Add support for ODFE 1.8 (Elasticsearch v7.7.0)
=> Add support for ODFE 1.8 (Elasticsearch v7.7.0)

.github/workflows/cd.yml
Build the release artifacts using Java 14
=> Build the release artifact using Java 14

build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.8.0.md, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.8.1.md
=> Update version to 1.8

build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.8.0.md, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.9.0.md
Build against elasticsearch 7.8
=> Build against elasticsearch 7.8

package.json
#29
Add assets from blessed to built executables.
See also: vercel/pkg#530
=> Add assets from blessed to built executables

release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.10.0.0.md
Add release notes for 1.10 release
=> Add release notes for 1.10 release

release-notes/opendistro-for-elasticsearch-perftop.release-notes-1.10.1.0.md
Update release notes for 1.10.1 release
=> Update release notes for 1.10.1 release

build.gradle, opendistro-for-elasticsearch.perftop.release-notes-1.11.0.0.md
Add support for 1.11.0.0 release
=> Add support for 1.11.0.0 release

build.gradle, package-lock.json, package.json, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.11.0.0.md, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.12.0.0.md
*Issue #, if available:* Changes for ODFE 1.12 release
1. Verified that build is passing
2. Verified that dashboards are coming up.
=> Adding changes for ODFE 1.12 release

.github/workflows/cd.yml, README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, package-lock.json, package.json, release-notes/opendistro-for-elasticsearch.perftop.release-notes-1.13.0.0.md
*Issue #, if available:* ODFE 1.13 Version Release #70
* Verified that build is passing
* Verified that dashboards are coming up.
=> Adding Changes for 1.13 Release 
